name: CI
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  nix-build:
    name: Build with Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src # Checkout the entire repo into a 'src' folder

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_version: 2.15.0

      # Run Nix build on your source directory
      - name: Build with Nix
        run: |
          nix-build src/default.nix # Adjust this path if needed
